include "structs.thrift"
include "commandResult.thrift"
namespace java com.github.geek29.geodethrift.management.service

service GeodeCommandService {

	commandResult.CommandResult alterDiskStore(1:structs.AlterDiskStoreArgs arguments),
	commandResult.CommandResult alterRegion(1:structs.AlterRegionArgs arguments),
	commandResult.CommandResult alterRuntime(1:structs.AlterRuntimeArgs arguments),
	commandResult.CommandResult backupDiskStore(1:structs.BackupDiskStoreArgs arguments),
	commandResult.CommandResult changeLoglevel(1:structs.ChangeLoglevelArgs arguments),
	commandResult.CommandResult clearDefinedIndexes(),
	commandResult.CommandResult closeDurableClient(1:structs.CloseDurableClientArgs arguments),
	commandResult.CommandResult closeDurableCq(1:structs.CloseDurableCqArgs arguments),
	commandResult.CommandResult compactDiskStore(1:structs.CompactDiskStoreArgs arguments),
	commandResult.CommandResult compactOfflineDiskStore(1:structs.CompactOfflineDiskStoreArgs arguments),
	commandResult.CommandResult configurePdx(1:structs.ConfigurePdxArgs arguments),
	commandResult.CommandResult createAsyncEventQueue(1:structs.CreateAsyncEventQueueArgs arguments),
	commandResult.CommandResult createDefinedIndexes(1:structs.CreateDefinedIndexesArgs arguments),
	commandResult.CommandResult createDiskStore(1:structs.CreateDiskStoreArgs arguments),
	commandResult.CommandResult createGatewayReceiver(1:structs.CreateGatewayReceiverArgs arguments),
	commandResult.CommandResult createGatewaySender(1:structs.CreateGatewaySenderArgs arguments),
	commandResult.CommandResult createHdfsStore(1:structs.CreateHdfsStoreArgs arguments),
	commandResult.CommandResult createIndex(1:structs.CreateIndexArgs arguments),
	commandResult.CommandResult createRegion(1:structs.CreateRegionArgs arguments),
	commandResult.CommandResult defineIndex(1:structs.DefineIndexArgs arguments),
	commandResult.CommandResult describeConfig(1:structs.DescribeConfigArgs arguments),
	commandResult.CommandResult describeDiskStore(1:structs.DescribeDiskStoreArgs arguments),
	commandResult.CommandResult describeMember(1:structs.DescribeMemberArgs arguments),
	commandResult.CommandResult describeOfflineDiskStore(1:structs.DescribeOfflineDiskStoreArgs arguments),
	commandResult.CommandResult describeRegion(1:structs.DescribeRegionArgs arguments),
	commandResult.CommandResult destroyDiskStore(1:structs.DestroyDiskStoreArgs arguments),
	commandResult.CommandResult destroyFunction(1:structs.DestroyFunctionArgs arguments),
	commandResult.CommandResult destroyIndex(1:structs.DestroyIndexArgs arguments),
	commandResult.CommandResult destroyRegion(1:structs.DestroyRegionArgs arguments),
	commandResult.CommandResult encryptPassword(1:structs.EncryptPasswordArgs arguments),
	commandResult.CommandResult executeFunction(1:structs.ExecuteFunctionArgs arguments),
	commandResult.CommandResult exportClusterConfiguration(1:structs.ExportClusterConfigurationArgs arguments),
	commandResult.CommandResult exportConfig(1:structs.ExportConfigArgs arguments),
	commandResult.CommandResult exportData(1:structs.ExportDataArgs arguments),
	commandResult.CommandResult exportLogs(1:structs.ExportLogsArgs arguments),
	commandResult.CommandResult exportOfflineDiskStore(1:structs.ExportOfflineDiskStoreArgs arguments),
	commandResult.CommandResult exportStackTraces(1:structs.ExportStackTracesArgs arguments),
	commandResult.CommandResult gc(1:structs.GcArgs arguments),
	commandResult.CommandResult get(1:structs.GetArgs arguments),
	commandResult.CommandResult help(1:structs.HelpArgs arguments),
	commandResult.CommandResult hint(1:structs.HintArgs arguments),
	commandResult.CommandResult history(1:structs.HistoryArgs arguments),
	commandResult.CommandResult listAsyncEventQueues(),
	commandResult.CommandResult listClients(),
	commandResult.CommandResult listDeployed(1:structs.ListDeployedArgs arguments),
	commandResult.CommandResult listDiskStores(),
	commandResult.CommandResult listDurableCqs(1:structs.ListDurableCqsArgs arguments),
	commandResult.CommandResult listFunctions(1:structs.ListFunctionsArgs arguments),
	commandResult.CommandResult listGateways(1:structs.ListGatewaysArgs arguments),
	commandResult.CommandResult listIndexes(1:structs.ListIndexesArgs arguments),
	commandResult.CommandResult listMembers(1:structs.ListMembersArgs arguments),
	commandResult.CommandResult listRegions(1:structs.ListRegionsArgs arguments),
	commandResult.CommandResult loadBalanceGatewaySender(1:structs.LoadBalanceGatewaySenderArgs arguments),
	commandResult.CommandResult locateEntry(1:structs.LocateEntryArgs arguments),
	commandResult.CommandResult netstat(1:structs.NetstatArgs arguments),
	commandResult.CommandResult pauseGatewaySender(1:structs.PauseGatewaySenderArgs arguments),
	commandResult.CommandResult pdxRename(1:structs.PdxRenameArgs arguments),
	commandResult.CommandResult put(1:structs.PutArgs arguments),
	commandResult.CommandResult query(1:structs.QueryArgs arguments),
	commandResult.CommandResult rebalance(1:structs.RebalanceArgs arguments),
	commandResult.CommandResult remove(1:structs.RemoveArgs arguments),
	commandResult.CommandResult resumeGatewaySender(1:structs.ResumeGatewaySenderArgs arguments),
	commandResult.CommandResult revokeMissingDiskStore(1:structs.RevokeMissingDiskStoreArgs arguments),
	commandResult.CommandResult setVariable(1:structs.SetVariableArgs arguments),
	commandResult.CommandResult showDeadLocks(1:structs.ShowDeadLocksArgs arguments),
	commandResult.CommandResult showLog(1:structs.ShowLogArgs arguments),
	commandResult.CommandResult showMetrics(1:structs.ShowMetricsArgs arguments),
	commandResult.CommandResult showMissingDiskStores(),
	commandResult.CommandResult showSubscriptionQueueSize(1:structs.ShowSubscriptionQueueSizeArgs arguments),
	commandResult.CommandResult shutdown(1:structs.ShutdownArgs arguments),
	commandResult.CommandResult statusClusterConfigService(),
	commandResult.CommandResult statusGatewayReceiver(1:structs.StatusGatewayReceiverArgs arguments),
	commandResult.CommandResult statusGatewaySender(1:structs.StatusGatewaySenderArgs arguments),
	commandResult.CommandResult statusLocator(1:structs.StatusLocatorArgs arguments),
	commandResult.CommandResult statusServer(1:structs.StatusServerArgs arguments),
	commandResult.CommandResult stopGatewayReceiver(1:structs.StopGatewayReceiverArgs arguments),
	commandResult.CommandResult stopGatewaySender(1:structs.StopGatewaySenderArgs arguments),
	commandResult.CommandResult stopLocator(1:structs.StopLocatorArgs arguments),
	commandResult.CommandResult stopServer(1:structs.StopServerArgs arguments),
	commandResult.CommandResult undeploy(1:structs.UndeployArgs arguments),
	commandResult.CommandResult upgradeOfflineDiskStore(1:structs.UpgradeOfflineDiskStoreArgs arguments),
	commandResult.CommandResult validateOfflineDiskStore(1:structs.ValidateOfflineDiskStoreArgs arguments),
	commandResult.CommandResult version(1:structs.VersionArgs arguments)
}